version: "3.10"

services:
  frontend:
    build: 
      dockerfile: frontend\Dockerfile
    ports:
      - 8501:8501
    depends_on:
      - app
    
  app:
    build: 
      dockerfile: app\Dockerfile
    ports:
      - 8000:8000